// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wailsapp} from '../models';

export function GetState():Promise<wailsapp.UIState>;

export function SetActive(arg1:boolean):Promise<void>;

export function SetBorderColor(arg1:number):Promise<void>;

export function SetBorderEnabled(arg1:boolean):Promise<void>;

export function SetBorderThickness(arg1:number):Promise<void>;

export function SetFollowCursor(arg1:boolean):Promise<void>;

export function SetHotkey(arg1:number):Promise<void>;

export function SetHotkeyMode(arg1:string):Promise<void>;

export function SetRenderBackend(arg1:string):Promise<void>;

export function SetScopeSize(arg1:number):Promise<void>;

export function SetZoomLevel(arg1:number):Promise<void>;

export function ToggleActive():Promise<void>;
