// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetState() {
  return window['go']['wailsapp']['App']['GetState']();
}

export function SetActive(arg1) {
  return window['go']['wailsapp']['App']['SetActive'](arg1);
}

export function SetBorderColor(arg1) {
  return window['go']['wailsapp']['App']['SetBorderColor'](arg1);
}

export function SetBorderEnabled(arg1) {
  return window['go']['wailsapp']['App']['SetBorderEnabled'](arg1);
}

export function SetBorderThickness(arg1) {
  return window['go']['wailsapp']['App']['SetBorderThickness'](arg1);
}

export function SetFollowCursor(arg1) {
  return window['go']['wailsapp']['App']['SetFollowCursor'](arg1);
}

export function SetHotkey(arg1) {
  return window['go']['wailsapp']['App']['SetHotkey'](arg1);
}

export function SetHotkeyMode(arg1) {
  return window['go']['wailsapp']['App']['SetHotkeyMode'](arg1);
}

export function SetRenderBackend(arg1) {
  return window['go']['wailsapp']['App']['SetRenderBackend'](arg1);
}

export function SetScopeSize(arg1) {
  return window['go']['wailsapp']['App']['SetScopeSize'](arg1);
}

export function SetZoomLevel(arg1) {
  return window['go']['wailsapp']['App']['SetZoomLevel'](arg1);
}

export function ToggleActive() {
  return window['go']['wailsapp']['App']['ToggleActive']();
}
